In [1]:
import pandas as pd
import numpy as np

In [2]:
infoTRIP=pd.read_csv('../data/trip_departure/processed/td_agg.csv')
infoTRIP

,ope_date,depot_id,line_id,bus_no,point_a,point_b,ttl_td_id,ttl_captain_id,ttl_point_a,ttl_point_b,...,avg_diff_minutes_idle_mode,avg_diff_minutes_to_point_a,med_diff_minutes_from_point_a,med_diff_minutes_idle_mode,med_diff_minutes_to_point_a,max_speed,min_speed,avg_speed,med_speed,ttl_td_completed
0,2022-10-01,10,K1000,CDH7753,H/BANDAR,GAMBANG RESORT,14,1,1,1,...,61.783333,68.311111,72.258333,57.675000,80.316667,28.0,8.0,16.181818,15.0,14.0
1,2022-10-01,10,K1000,CDD1442,H/BANDAR,GAMBANG RESORT,12,1,1,1,...,32.366667,88.500000,73.366667,41.483333,82.150000,56.0,15.0,24.090909,19.0,12.0
2,2022-10-01,10,K1000,CDH2338,H/BANDAR,GAMBANG RESORT,12,1,1,1,...,57.560000,60.505556,83.266667,51.216667,62.033333,59.0,8.0,21.777778,17.0,12.0
3,2022-10-01,10,K1000,CDH5966,H/BANDAR,GAMBANG RESORT,12,1,1,1,...,53.123333,70.572222,76.666667,44.350000,71.983333,45.0,8.0,17.083333,14.0,12.0
4,2022-10-01,10,K1000,CDH7750,H/BANDAR,GAMBANG RESORT,8,1,1,1,...,24.000000,86.300000,94.383333,18.483333,86.300000,56.0,6.0,21.285714,16.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11542,2022-10-21,5,U5900,WB759L,BANDAR SUNGAI LONG,LEBUH PUDU,16,1,1,1,...,29.302381,82.491667,72.250000,8.500000,74.741667,46.0,1.0,25.142857,29.0,16.0
11543,2022-10-21,5,U4000,WA1376G,DAMAI PERDANA,HUB LEBUH PUDU via B,10,1,1,1,...,18.900000,89.827778,63.291667,7.391667,75.350000,35.0,4.0,14.700000,13.0,10.0
11544,2022-10-21,5,U6500,WPV6981,KL Santral (Petron),Pasar Seni,32,1,1,1,...,13.816667,70.683333,5.500000,3.500000,69.241667,24.0,1.0,11.611111,11.5,32.0
11545,2022-10-21,2,U1910,WUX5671,SRI SEGAMBIUT,CHOW KIT,43,2,1,1,...,14.519048,33.007576,29.250000,7.500000,33.000000,38.0,1.0,15.846154,13.0,43.0
11546,2022-10-21,2,U1910,WUW8426,SRI SEGAMBIUT,CHOW KIT,48,2,1,1,...,13.479710,32.330556,30.750000,8.500000,31.250000,41.0,1.0,15.617647,15.5,48.0

In [3]:
infoBAS=pd.read_csv('../data/processed/InfoBAS.csv')
infoBAS

c:\Users\izard\anaconda3\envs\pytorch\lib\site-packages\IPython\core\interactiveshell.py:3457: DtypeWarning: Columns (26) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ope_date,depot_id,line_id,bus_no,br_id,br_repair_status,br_entry_status,br_date,br_date_entry,br_target_completed,...,fc_remark,label_3,date_issues,capt_id,bcc_acc_id,acc_date,bus_damage,eng_find,label_1,label
0,2022-10-01,10,K1000,CDH7753,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal trip
1,2022-10-01,10,K1000,CDD1442,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal trip
2,2022-10-01,10,K1000,CDH2338,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal trip
3,2022-10-01,10,K1000,CDH5966,1129191.0,MAJOR,BAS MENYENTAP MASA MEMANDU,2022-10-01,2022-10-01,2022-10-02,...,NaN,NaN,2022-10-01,NaN,NaN,NaN,NaN,NaN,NaN,engine repair
4,2022-10-01,10,K1000,CDH7750,1129194.0,SCH.PM,SERVIS A,2022-10-01,2022-10-01,2022-10-02,...,NaN,NaN,2022-10-01,NaN,NaN,NaN,NaN,NaN,NaN,engine repair
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
358143,2022-09-30,7,T7910,WVA2966,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal trip
358144,2022-09-30,7,T8500,WUT8479,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal trip
358145,2022-09-30,7,T8500,WVD3251,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,return to depot,2022-09-30,NaN,NaN,NaN,NaN,NaN,NaN,return to depot
358146,2022-09-30,7,T8500,WVE5806,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal trip
358147,2022-09-30,7,T7820,WVD2353,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal trip

In [6]:
pd.merge(infoTRIP,infoBAS.drop(columns=['label_1','label_2','label_3']),how='left',on=['ope_date','depot_id','bus_no']).to_csv('../data/model/data_model.csv',index=False)