In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [3]:
pd.read_csv('../data/accident.csv') # lat lon accident to plot

,bcc_acc_id,acc_date,time_report,event_time,event_loc,location_cat,bus_no,body_no,bus_model_id,route_id,depot_id,capt_id,third_party,cat_id,injury,third_party2,spad_case,bus_damage,immediate_cause,catitan,remark,pax,public,staff,status,report_date,guilty,penalty,cost,act_taken,cso_duty,category_acc,acc_sn,telegram_desc,fin_impact,ope_impact,ops_find,eng_find,conclusion_close,accstatus,dt_created,dt_modified,modified_by
0,14686,2022-01-01,0 days 07:23:00,0 days 07:19:00,HADAPAN BALAI POLIS PEKAN AI ITAM,3.0,PJJ7237,-,26,238,12,KTATUPUK,KERETA - PMW5076,7,NaN,NaN,NO,TIADA KEROSAKAN / TIADA KECEDERAAN,3.0,SEBUAH KERETA MELANGGAR BAS,SEBUAH KERETA YANG HENDAK KELUAR DARI PARKING ...,0,0,0,1,2022-01-01,0,6,NIL,7.0,MOHAMAD MAZIKI BIN KHAZALI,MINOR,ACC12220101S70001,NaN,0.0,1.0,BC Tidak Bersalah\r\n,Non mechanical failure\r\n,2.0,1.0,2022-01-01 07:37:29,2022-08-09 16:02:54,NaN
1,14688,2022-01-01,0 days 08:30:00,0 days 08:30:00,JALAN BESERAH,3.0,CDH7746,NaN,13,227,10,FWNVJNSM,NaN,8,NaN,NaN,NO,CERMIN SISI PECAH,1.0,TERLANGGAR DAHAN POKOK TUMBANG DI ATAS JALAN,NaN,0,0,0,1,2022-01-01,0,1,RM95.00,1.0,NUR NADILA MOHD NOR,MINOR,ACC10220101SK5003,NaN,0.0,1.0,Siasatan telah dilakukan keatas kapten pada 05...,NaN,2.0,1.0,2022-01-01 10:08:42,2023-08-01 17:15:34,NaN
2,14689,2022-01-02,0 days 07:30:00,0 days 07:00:00,"Bus Stop Guan ying temple, Jalan Pahang (OD: L...",3.0,WUW1702,L205,2,877,2,BTYCWGIS,Motorsikal BQS2858,4,NaN,NaN,NO,Bumper belakang kanan pecah,3.0,Dilanggar motorsikal,"Semasa BC sedang menurunkan penumpang, tiba-ti...",0,26,0,1,2022-01-02,0,6,RM362.17,7.0,NORKHATINA BINTI MOHD RAZALI,MINOR,ACC02220102KLG001,NaN,NaN,NaN,kecuaian pihak ketiga menyebabkan kemalangan,non mechanical failure,2.0,1.0,2022-01-02 07:44:20,2022-08-02 16:21:26,NaN
3,14690,2022-01-03,0 days 09:47:00,0 days 09:45:00,JALAN TELUK KUMBAR- HADAPAN SJKC YANG CHENG,2.0,PJG4312,-,26,263,14,FOXUZEQW,LORI TANAH - PHJ9211,7,NaN,NaN,NO,BUCU BELAKANG SEBELAH KANAN PECAH / TIADA KECE...,3.0,SEBUAH LORI MELANGGAR BAS,SEBUAH LORI TELAH MENLANGGAR BELAKANG BAS KETI...,0,0,0,1,2022-01-03,0,6,RM2680.61,7.0,ABD RAHMAN BIN AHMAD,MINOR,ACC14220103S70001,NaN,0.0,1.0,BC Tidak Bersalah\r\n,Non mechanical failure\r\n,2.0,1.0,2022-01-03 09:58:50,2022-08-09 16:21:32,NaN
4,14691,2022-01-03,0 days 14:36:00,0 days 14:30:00,Jalan Raja Laut hala Dato Senu (OD: PASAR SENI...,3.0,WVC4291,L288,2,874,2,VTZFMSRN,NaN,8,NaN,NaN,NO,Cermin pintu penumpang hadapan pecah,1.0,Bas dibaling objek keras oleh orang awam,Semasa kejadian terdapat 8 orang penumpang di ...,0,0,0,1,2022-01-03,0,6,RM546.00,7.0,NORKHATINA BINTI MOHD RAZALI,MINOR,ACC02220103KLG002,Cermin pintu penumpang hadapan pecah\r\n\r\nSe...,NaN,NaN,Tiada kecuaian dari kapten bas dan suspect yan...,non mechanical failure,2.0,1.0,2022-01-03 14:51:32,2022-08-02 16:17:03,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2251,16948,2023-06-30,0 days 06:25:00,0 days 06:00:00,MRT FEEDER BUS KAJANG DEPOT,1.0,VX3625,NaN,25,805,22,JWEDCNVZ,NaN,7,NaN,NaN,NO,BAHAGIAN CERMIN BELAKANG SEBELAH KANAN BAS PECAH,4.0,BAS DILANGGAR BAS MRT KAJANG (VX3035) KETIKA B...,BAS DILANGGAR BAS MRT KAJANG (VX3035) KETIKA B...,0,0,0,1,2023-06-30,0,1,RM938.11,1.0,MUHAMAD AFIQ BIN RAZALI,MINOR,ACC22230630S5M002,BAHAGIAN CERMIN BELAKANG SEBELAH KANAN BAS PECAH,0.0,1.0,HASIL SIASATAN YANG DIJALANKAN PIHAK DEPOH MEN...,NaN,2.0,1.0,2023-06-30 06:54:03,2023-07-13 18:14:50,NaN
2252,16949,2023-06-30,0 days 08:51:00,0 days 08:49:00,KAMPUNG PISANG,3.0,PKX3372,-,13,238,12,HBFXIBCN,NaN,8,NaN,NaN,NO,TIADA KEROSAKAN,5.0,SEORANG PENUMPANG PEREMPUAN TERJATUH DI DALAM BAS,SEORANG PENUMPANG PEREMPUAN DALAM LINGKUNGAN U...,20,0,0,1,2023-06-30,0,6,0,7.0,THAVABALAN A/L LOHGANATHAN,MINOR,ACC12230630SK5003,SEORANG PENUMPANG PEREMPUAN DALAM LINGKUNGAN U...,0.0,1.0,Bc not guilty,Non mechanical faillure,2.0,1.0,2023-06-30 09:22:11,2023-07-20 12:30:32,NaN
2253,16950,2023-06-30,0 days 12:54:00,0 days 12:19:00,Berhampiran Winnie Plaza Jalan Sg.Chua (OD : B...,3.0,WB915L,S731,10,598,5,ERXHQQHN,NaN,8,NaN,NaN,NO,Cermin pintu penumpang hadapan pecah,1.0,Tergesel penghadang jalan,Laporan awal dari kapten memaklumkan semasa se...,0,0,0,1,2023-06-30,2,1,"RM 8,700.99",3.0,NOR AQILAH BINTI KHAMIS,MINOR,ACC05230630S5A004,Cermin pintu penumpang hadapan pecah\r\n\r\nLa...,0.0,1.0,Hasail siasatan dari rakaman CCTV di dapati BC...,NaN,2.0,1.0,2023-06-30 12:54:24,2023-07-21 09:26:13,NaN
2254,16951,2023-06-30,0 days 15:06:00,0 days 15:00:00,PEKAN AIR ITAM- BERHADAPAN 7-ELEVEN,3.0,PLV1635,-,10,235,12,BXIANLKH,NaN,7,NaN,NaN,NO,CALAR DIBAHAGIAN BODY BELAKANG KANAN,2.0,-,INFO DARI BC SEMASA DALAM PERJALANAN DI PEKAN ...,0,0,0,1,2023-06-30,0,6,RM364.51,7.0,MUHAMMAD AMIRUL BIN MAZLAN,MINOR,ACC12230630S5A005,INFO DARI BC SEMASA DALAM PERJALANAN DI PEKAN ...,0.0,1.0,Bc not guilty - Tiada saman dikeluarkan oleh P...,Non mechanical faillure,2.0,1.0,2023-06-30 15:27:06,2023-07-04 11:07:14,NaN
2255,16952,2023-06-30,0 days 23:30:00,0 days 22:35:00,"LAMPU ISYARAT SIMPANG BALAK, JALAN CHERAS",3.0,VK2745,NaN,25,770,22,CUCFPFKN,NaN,7,NaN,NaN,NO,BAHAGIAN BELAKANG BADAN BAS SEBELAH KANAN CALAR,2.0,BAS MELANGGAR KERETA PERODUA BEZZA (QLB4026) K...,BAS MELANGGAR KERETA PERODUA BEZZA (QLB4026) K...,0,0,0,1,2023-06-30,2,1,RM517.01,1.0,ROSLINDA JUPRI,MINOR,ACC22230630S5M006,BAHAGIAN BELAKANG BADAN BAS SEBELAH KANAN CALA...,0.0,1.0,HASIL SIASATAN YANG DIJALANKAN PIHAK DEPOH MEN...,NaN,2.0,1.0,2023-06-30 23:54:07,2023-07-13 18:17:19,NaN

In [4]:
pd.read_csv('../data/bus_stop_list.csv') # to integrate lat lon for bus stop into boundary map

,bus_stop_id,stop_id,stop_name,street_name,gpsx_coordinate,gpsy_coordinate,use,latitude,longitude,enter_angle,stop_variant
0,1,1000001,KL129 FLAT DESA AMAN (OPP),JLN DESA AMAN,10144.340780,305.874180,Y,3.097903,101.739013,349.0,NaN
1,2,1000002,SL254 PERINDUSTRIAN BT CAVES,JLN SBC 5,10141.227992,314.016151,Y,3.233603,101.687133,270.0,NaN
2,3,1000003,KL1869 TAMAN LAWA,JLN D,10139.922980,311.920140,Y,3.198669,101.665383,290.0,NaN
3,4,1000004,KL199 KG SRI DELIMA,JLN 17/42,10139.996241,311.944784,Y,3.199080,101.666604,198.0,NaN
4,5,1000005,AJ49 MERDEKA PLACE,JLN MERDEKA,10145.862560,308.342760,Y,3.139046,101.764376,203.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
10394,12473,1008696,DESA MENTARI BLOK 3,JLN PJS 5/12,10137.170180,304.716240,Y,3.078604,101.619503,256.0,NaN
10395,12474,1008697,DESA MENTARI BLOK 7,JLN PJS 6/5G,10137.152360,304.799580,Y,3.079993,101.619206,27.0,NaN
10396,12475,1008698,MASJID JUMHURIAH,JLN PJS 2/7,10138.224500,304.938900,Y,3.082315,101.637075,193.0,NaN
10397,12476,1008699,PUSAT KOMERSIAL (MATAHARI MALL),JLN PJS 2/7,10138.207160,304.810560,Y,3.080176,101.636786,188.0,NaN
10398,12477,1008700,SMK DATO HARUN/KLINIK KESIHATAN TAMAN MEDAN,JLN PJS 2/2,10138.094900,304.704540,Y,3.078409,101.634915,282.0,NaN

In [5]:
pd.read_csv('../data/depot.csv') # to create state name columns , parliamentary boundary columns ,

,depot_id,depot_name,state_id,depot_status,category,zone,code
0,1,Sentul,1,0,1,RKL,STL
1,2,Batu Caves,1,1,1,RKL,BCV
2,3,Melawati,1,0,1,RKL,MLW
3,4,Maluri,1,1,1,RKL,MLR
4,5,Cheras Selatan,1,1,1,RKL,CHS
5,6,OKR,1,0,1,RKL,OKR
6,7,Shah Alam,1,1,1,RKL,SHA
7,8,Asia Jaya,1,0,1,RKL,ASJ
8,9,Kepong,1,0,1,RKL,KPG
9,10,Kuantan,8,1,1,RKN,SMB
10,11,Tanjung Bungah,5,1,1,RPG,TB
11,12,Sungai Nibong,5,1,1,RPG,SN
12,13,Weld Quay,5,1,1,RPG,WQ
13,14,Balik Pulau,5,1,1,RPG,BP
14,15,Mak Mandin,5,1,1,RPG,MM
15,16,Nibong Tebal,5,1,1,RPG,NT
16,17,Lorong Kulit,5,1,1,RPG,LK
17,18,BRT Sunway,1,1,2,BRT,SWY
18,19,Kamunting,5,0,1,RPG,KM
19,20,Academy,1,0,0,ACD,AC
20,21,MRT Sungai Buloh,1,1,3,MRT,SGB
21,22,MRT Kajang,1,1,3,MRT,KJG
22,23,Manjung,5,0,1,RPG,MJ
23,24,Sungai Petani,5,0,1,RPG,SP
24,25,Central Workshop CHS,1,0,0,RKL,CWCS
25,26,MRT Jinjang,1,1,3,MRT,JJG
26,27,MRT Serdang,1,1,1,RKL,SDG
27,28,Putrajaya,1,1,1,RKL,PTJ

In [6]:
pd.read_csv('../data/eng_bus_repair.csv')

c:\Users\izard\anaconda3\envs\pytorch\lib\site-packages\IPython\core\interactiveshell.py:3457: DtypeWarning: Columns (15,22,23) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,br_id,br_date,br_timetype,depot_id,loc_code,br_busno,br_bus_status,br_date_entry,br_repair_status,br_entry_status,br_current_status,br_waiting_part,br_waiting_services,br_warranty,br_nt_no,br_mo_no,br_target_completed,br_date_roadtax,br_date_puspakom,br_remark,dt_created,dt_modified,br_mh_remark,dt_mh_modified
0,974044,2022-01-01,AM,2,CWS,PJH4804,RTW,2021-12-05,MAJOR,BD- ENGINE FAULTY,SEND CWS ON 29.12.2021,No,No,No,200492504,11198733,2022-01-31,2022-04-05,2022-04-05,NaN,2022-01-01 00:00:50,2022-01-01 07:25:52,NaN,NaN
1,974045,2022-01-01,AM,2,CWS,PJJ1894,RTW,2021-05-25,MAJOR,BDW-SKRU COMPRESSOR TANGGAL /ENGINE BUNYI KASAR,SEND TO CW AT 23/8/2021,No,No,No,200466638,11147714,2022-01-31,2021-08-15,2021-08-15,NaN,2022-01-01 00:00:50,2022-01-01 07:25:52,NaN,NaN
2,974046,2022-01-01,AM,2,CWS,PJJ4919,RTW,2021-12-08,MAJOR,GEAR BOX PROBLEM- GEAR SLIP,Send CWS on date 30.12.2021,No,No,No,200493032,11199657,2022-01-28,2022-05-11,2022-05-11,NaN,2022-01-01 00:00:50,2022-01-01 07:25:52,NaN,NaN
3,974047,2022-01-01,AM,2,CWS,WUW1356,RTW,2021-11-02,MAJOR,ENGINE FAULTY- TIMING GEAR,SEND CWS 09.11.2021 TO PROGRESS REPAIR,No,No,No,11189367,11860613,2022-01-31,2021-11-20,2021-11-20,COPERATE LIVERY (FROM GOKL),2022-01-01 00:00:50,2022-01-01 07:25:52,NaN,NaN
4,974048,2022-01-01,AM,2,CWS,WVA4383,RTW,2021-11-19,MAJOR,ENGINE SYSTEM FAULTY,SEND CWS ON DATE 23.11.2021,No,No,No,200490200,11194239,2022-01-31,2022-05-03,2022-05-03,NaN,2022-01-01 00:00:50,2022-01-01 07:25:52,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327357,1352630,2023-04-26,PM,27,KJG,VAE7340,RTW,2023-04-17,INC.REPAIR,SIDE PANEL BODY KIRI TERKOPAK,IN PROGRESS,No,No,No,NaN,NaN,2023-05-17,2024-01-10,2024-01-10,NaN,2023-08-10 15:53:13,NaN,NaN,NaN
327358,1352631,2023-04-26,PM,27,SDG,PJJ5202,RTW,2023-02-01,PUSPAKOM,OPEN DATE B2,IN PROGRESS,No,No,No,NaN,NaN,2023-05-18,2023-11-18,2023-11-18,NaN,2023-08-10 15:53:13,NaN,NaN,NaN
327359,1352632,2023-04-26,PM,27,KJG,WVD1492,RTW,2023-04-26,PUSPAKOM,PUSPAKOM INSPECTION,IN PROGRESS,No,No,No,NaN,NaN,2023-04-26,2023-10-30,2023-10-30,NaN,2023-08-10 15:53:13,NaN,NaN,NaN
327360,1352633,2023-04-26,PM,27,KJG,WUY4969,RTW,2023-04-26,PUSPAKOM,PUSPAKOM INSPECTION,IN PROGRESS,No,No,No,NaN,NaN,2023-04-26,2023-11-03,2023-11-03,NaN,2023-08-10 15:53:13,NaN,NaN,NaN
327361,1352634,2023-04-26,PM,27,KJG,CDH7532,RTW,2023-04-26,PUSPAKOM,PUSPAKOM INSPECTION,IN PROGRESS,No,No,No,NaN,NaN,2023-04-26,2023-10-26,2023-10-26,NaN,2023-08-10 15:53:13,NaN,NaN,NaN

In [8]:
pd.read_csv('../data/route_busstop.csv') #to aggregate route id distance

,route_busstop_id,depot,route_id,route_no,line_id,bus_stop_id,stop_id,order,stop_category,border,hub_stop,ride_zone,alight_zone,entering_angle,distance,popular,municipal,dr,dt_created
0,1384,5,484,452,U452002,1606.0,1001609,1,NaN,N,N,1,1,270.0,0,NaN,NaN,1,2020-03-09 11:10:44
1,1385,5,484,452,U452002,108.0,1000108,2,NaN,N,N,1,1,269.0,500,NaN,NaN,1,2020-03-09 11:10:44
2,1386,5,484,452,U452002,3847.0,1003854,3,NaN,N,N,1,1,349.0,2000,NaN,NaN,1,2020-03-09 11:10:44
3,1387,5,484,452,U452002,1714.0,1001717,4,NaN,N,N,1,1,338.0,2400,NaN,NaN,1,2020-03-09 11:10:44
4,1388,5,484,452,U452002,3308.0,1003313,5,NaN,N,N,1,1,342.0,2700,NaN,NaN,1,2020-03-09 11:10:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14323,70884,28,1078,P108,P108002,11685.0,1005602,29,NaN,N,N,1,1,NaN,16626,NaN,NaN,2,2023-08-22 11:06:15
14324,70885,28,1078,P108,P108002,11686.0,1005603,30,NaN,N,N,1,1,NaN,16989,NaN,NaN,2,2023-08-22 11:06:15
14325,70886,28,1078,P108,P108002,11733.0,1005650,31,NaN,N,N,1,1,NaN,17647,NaN,NaN,2,2023-08-22 11:06:15
14326,70887,28,1078,P108,P108002,11734.0,1005651,32,NaN,N,N,1,1,NaN,17982,NaN,NaN,2,2023-08-22 11:06:15
14327,70888,28,1078,P108,P108002,11667.0,1005584,33,NaN,N,N,1,1,NaN,19500,NaN,NaN,2,2023-08-22 11:06:15

In [9]:
pd.read_csv('../data/route.csv') #to aggregate route id distance

,route_id,route_no,route_no_cbts,route_origin,route_destination,route_type,route_category,route_service,route_corridor,route_name,route_desc,route_dist_in,route_dist_out,state_id,depot_id,status,freq_min,freq_max,total_km,km_per_trip,travel_time,deadmileage,line_id,zone,pis_profile
0,1,B103,XB1030,NaN,NaN,0,Normal,RAPID,NaN,NONAME,TITIWANGSA - BKT BINTANG via KG BARU,NaN,NaN,1,1,5,0.0,0.0,15.2,NaN,0.0,NaN,NaN,0,NaN
1,2,B112,XB1120,NaN,NaN,0,Normal,RAPID,NaN,NONAME,KL SENTRAL - MALURI,NaN,NaN,1,1,5,0.0,0.0,19.3,NaN,0.0,NaN,NaN,0,NaN
2,3,B114,XB1140,NaN,NaN,0,Normal,RAPID,NaN,NONAME,MALURI - TITIWANGSA via KLCC,NaN,NaN,1,1,5,0.0,0.0,22.8,NaN,0.0,NaN,NaN,0,NaN
3,4,B115,XB1150,NaN,NaN,0,Normal,RAPID,NaN,NONAME,JLN SULTAN MOHD - PARLIMEN,NaN,NaN,1,1,5,0.0,0.0,18.5,NaN,0.0,NaN,NaN,0,NaN
4,5,U1,XU0010,NaN,NaN,UTAMA,Normal,RAPID,NaN,NONAME,PINGGIRAN BT CAVES - CHOW KIT,NaN,NaN,1,1,5,0.0,0.0,33.6,NaN,0.0,NaN,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
977,1165,MS02,H4200,MRT PUTRAJAYA SENTRAL,KOMPLEKS NASYRUL QURAN,OTHER,NaN,RAPID,NaN,NaN,MRT Putrajaya Sentral ~ Kompleks Nasyrul Quran,NaN,24800.0,1,4,1,NaN,NaN,NaN,NaN,NaN,64.5,NaN,0,NaN
978,1166,MS02,H4200,MRT PUTRAJAYA SENTRAL,KOMPLEKS NASYRUL QURAN,OTHER,NaN,RAPID,NaN,NaN,MRT Putrajaya Sentral ~ Kompleks Nasyrul Quran,NaN,24800.0,1,22,1,NaN,NaN,NaN,NaN,NaN,64.5,NaN,0,NaN
979,1167,MS03,H4300,MRT PUTRAJAYA SENTRAL,MARINA PUTRAJAYA,OTHER,NaN,RAPID,NaN,NaN,MRT Putrajaya Sentral ~ Marina Putrajaya,NaN,23700.0,1,5,1,NaN,NaN,NaN,NaN,NaN,64.5,NaN,0,NaN
980,1168,MS03,H4300,MRT PUTRAJAYA SENTRAL,MARINA PUTRAJAYA,OTHER,NaN,RAPID,NaN,NaN,MRT Putrajaya Sentral ~ Marina Putrajaya,NaN,23700.0,1,4,1,NaN,NaN,NaN,NaN,NaN,64.5,NaN,0,NaN
981,1169,MS03,H4300,MRT PUTRAJAYA SENTRAL,MARINA PUTRAJAYA,OTHER,NaN,RAPID,NaN,NaN,MRT Putrajaya Sentral ~ Marina Putrajaya,NaN,23700.0,1,22,1,NaN,NaN,NaN,NaN,NaN,64.5,NaN,0,NaN

In [11]:
#rtd=
pd.read_csv('../data/rtd.csv') #to hi lite descriptive stat for repair cause , need an etl to standardize
#rtd.iloc[0,0]

,rtd_id,rtd_date,rtd_time,depot_id,route_id,bus_no,bus_model_id,driver_id,reason_rtd,cases,...,tech_remark,time_arrived,fc_remark,rtd_sap_id,ope_approvedby,ope_remark,status,rtd_sn,telegram_desc,dt_created
0,209514,2022-01-01,0 days 05:50:00,5,671,WQR7493,31,TNZITDWB,NaN,1.0,...,NaN,0 days 06:00:00,Bus Repair and Captain Continue Duty With New Bus,2.004964e+08,NaN,NaN,1,RTD05220101B7L001,Lambang stop menyala,2022-01-01 05:51:13
1,209515,2022-01-01,0 days 06:53:00,15,278,PJH224,26,ATPBIKBV,NaN,5.0,...,NaN,0 days 07:15:00,Bus Repair and Captain Continue Duty With New Bus,NaN,NaN,NaN,1,RTD15220101S70002,LED TIDAK BERFUNGSI,2022-01-01 06:59:06
2,209516,2022-01-01,0 days 07:02:00,22,775,VH4089,25,TQFDAFVP,NaN,1.0,...,NaN,0 days 07:30:00,Bus Repair and Captain Continue Duty With New Bus,2.004964e+08,NaN,NaN,1,RTD22220101S5M003,AIR SYSTEM PROBLEM,2022-01-01 07:03:32
3,209517,2022-01-01,0 days 07:03:00,2,851,PJK2722,26,JTRDUIHR,NaN,1.0,...,NaN,0 days 08:20:00,Bus Repair and Captain Continue Duty With New Bus,2.004964e+08,NaN,NaN,1,RTD02220101S70004,Aircond panas,2022-01-01 07:03:34
4,209518,2022-01-01,0 days 07:02:00,22,869,VK6258,25,YTTUSFTH,NaN,1.0,...,NaN,0 days 07:50:00,Bus Repair and Captain Continue Duty With New Bus,2.004964e+08,NaN,NaN,1,RTD22220101S5M005,DOOR PROBLEM,2022-01-01 07:04:49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41824,251377,2023-06-30,0 days 22:02:00,4,865,W4087R,24,GMBMUENV,NaN,1.0,...,NaN,0 days 23:00:00,Bus Repair and Captain End Duty,2.306305e+09,NaN,NaN,1,RTD04230630S5B073,Airbellow depan bocor,2023-06-30 22:11:39
41825,251378,2023-06-30,0 days 00:00:00,7,729,WVD4738,9,TJTCDBWB,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1,RTD07230630SK7074,BC sakit perut,2023-06-30 22:14:48
41826,251379,2023-06-30,0 days 22:15:00,4,477,W4860W,24,BVHKWEDQ,NaN,1.0,...,NaN,0 days 23:00:00,Bus Repair and Captain End Duty,2.306305e+09,NaN,NaN,1,RTD04230630S5B075,ABS Malfunction,2023-06-30 22:16:18
41827,251380,2023-06-30,0 days 23:00:00,5,679,WPV4598,31,VJVCJPMM,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1,RTD05230630B7L076,compressor aircond malfunction,2023-06-30 23:01:25
41828,251436,2023-06-01,0 days 13:36:00,22,869,VH4108,25,ACLVPFXS,NaN,1.0,...,NaN,0 days 14:30:00,Bus Repair and Captain Continue Duty With New Bus,2.005845e+08,NaN,NaN,1,RTD22230701S5M056,FRONT PASSENGER DOOR PROBLEM,2023-07-01 15:06:51

In [8]:
import pandas as pd
import numpy as np

temp=pd.DataFrame()
print(temp.iloc[0,0])

IndexError: single positional indexer is out-of-bounds